import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import AboutMe from "../components/AboutMe";
import Projects from "../components/Projects";
import ContactMe from "../components/ContactMe";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
      </div>
      <main>
        <div className="flex justify-center items-center">
          <AboutMe />
        </div>
        <div className="flex justify-center items-center">
          <Projects />
        </div>
        <div>
          <ContactMe />
        </div>
      </main>
      <footer className="flex justify-center items-center text-gray-500 p-10 pb-5">
        ©Copyright 2022 Tomato Wilbur Yap
      </footer>
    </>
  );
}
